// <auto-generated />
namespace TesteBanco.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Tirando : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tirando));
        
        string IMigrationMetadata.Id
        {
            get { return "202004291954407_Tirando"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
